version: 2

jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Build image
          command: docker build -t proxy .
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
      - run:
          name: Push image to GCR
          command: |
            gcloud --quiet auth configure-docker
                  
            LATEST_TAG=gcr.io/api-circleci-test/proxy:latest
            docker tag proxy $LATEST_TAG
            docker push $LATEST_TAG

workflows:
  version: 2
  build-workflow:
    jobs:
      - build